--- 
sudo: required 

language: python

python: 
  - "2.7"

env: 
  - distribution: centos
    version: 7
  - distribution: ubuntu
    version: xenial
  - distribution: ubuntu
    version: trusty

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'
  - sudo apt-get install -y sshpass

install: 
  - pip install ansible==2.4.3.0


script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup -p 127.0.0.1:1234:22 ${distribution}-${version}:ansible > "${container_id}"'
  - ansible-galaxy install coadunate.devtools -p "${PWD}"/roles
  - env ANSIBLE_CONFIG="${PWD}"/tests/ansible.cfg ansible-playbook -v -i tests/inventory tests/test.yml
  - 'sudo docker rm -f "$(cat ${container_id})"'
