---

- name: make sure software directory exists
  file: path={{ ansible_env.PWD }}/software state=directory mode=0777

- name: fetch nanopolish from github 
  git: 
    repo: 'https://github.com/jts/nanopolish.git'
    dest: "{{ ansible_env.PWD }}/software/nanopolish"
    clone: yes

- name: make nanopolish 
  make:
    chdir: "{{ ansible_env.PWD }}/software/nanopolish"
    target: all

- name: add nanopolish to PATH 
  shell: echo export PATH={{ ansible_env.PWD }}/software/nanopolish:$PATH >> {{ ansible_env.PWD }}/.bashrc
  args: 
    chdir: "{{ ansible_env.HOME }}"
   


