FROM ubuntu:pangolin

RUN apt-get update 

RUN apt-get install -y \
    openssh-server
RUN mkdir /var/run/sshd

RUN echo 'root:toor' | chpasswd
RUN sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
RUN echo 'sshd: ALL' >> /etc/hosts.allow

CMD ["/usr/sbin/sshd", "-D"]
